// source: protos/test2.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

import * as jspb from 'google-protobuf';
import * as goog from 'closure-library/closure/goog';

import * as protos_test_pb from '../protos/test.js';
export class TestExtensionsMessage extends jspb.Message {
  /**
   * Generated by JsPbCodeGenerator.
   * @param {Array=} opt_data Optional initial data array, typically from a
   * server response, or constructed directly in Javascript. The array is used
   * in place and becomes part of the constructed object. It is not cloned.
   * If no data is provided, the constructed object will be empty, but still
   * valid.
   * @extends {jspb.Message}
   * @constructor
   */
  constructor(opt_data) {
    jspb.Message.initialize(this, opt_data, 0, 2, null, null);
  };
  /**
   * optional int32 intfield = 1;
   * @return {number}
   */
  getIntfield() {
    return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
  };


  /**
   * @param {number} value
   * @return {!TestExtensionsMessage} returns this
   */
  setIntfield(value) {
    return jspb.Message.setField(this, 1, value);
  };


  /**
   * Clears the field making it undefined.
   * @return {!TestExtensionsMessage} returns this
   */
  clearIntfield() {
    return jspb.Message.setField(this, 1, undefined);
  };


  /**
   * Returns whether this field is set.
   * @return {boolean}
   */
  hasIntfield() {
    return jspb.Message.getField(this, 1) != null;
  };


  /**
   * Deserializes binary data (in protobuf wire format).
   * @param {jspb.ByteSource} bytes The bytes to deserialize.
   * @return {!TestExtensionsMessage}
   */
  static deserializeBinary(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new TestExtensionsMessage;
    return TestExtensionsMessage.deserializeBinaryFromReader(msg, reader);
  };


  /**
   * Deserializes binary data (in protobuf wire format) from the
   * given reader into the given message object.
   * @param {!TestExtensionsMessage} msg The message object to deserialize into.
   * @param {!jspb.BinaryReader} reader The BinaryReader to use.
   * @return {!TestExtensionsMessage}
   */
  static deserializeBinaryFromReader(msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      var field = reader.getFieldNumber();
      switch (field) {
      case 1:
        var value = /** @type {number} */ (reader.readInt32());
        msg.setIntfield(value);
        break;
      default:
        jspb.Message.readBinaryExtension(msg, reader,
          TestExtensionsMessage.extensionsBinary,
          TestExtensionsMessage.prototype.getExtension,
          TestExtensionsMessage.prototype.setExtension);
        break;
      }
    }
    return msg;
  };


  /**
   * Serializes the message to binary data (in protobuf wire format).
   * @return {!Uint8Array}
   */
  serializeBinary() {
    var writer = new jspb.BinaryWriter();
    TestExtensionsMessage.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
  };


  /**
   * Serializes the given message to binary data (in protobuf wire
   * format), writing to the given BinaryWriter.
   * @param {!TestExtensionsMessage} message
   * @param {!jspb.BinaryWriter} writer
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  static serializeBinaryToWriter(message, writer) {
    var f = undefined;
    f = /** @type {number} */ (jspb.Message.getField(message, 1));
    if (f != null) {
      writer.writeInt32(
        1,
        f
      );
    }
    jspb.Message.serializeBinaryExtensions(message, writer,
      TestExtensionsMessage.extensionsBinary, TestExtensionsMessage.prototype.getExtension);
  };


}

if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  TestExtensionsMessage.displayName = 'proto.jspb.test.TestExtensionsMessage';
}

/**
 * The extensions registered with this message class. This is a map of
 * extension field number to fieldInfo object.
 *
 * For example:
 *     { 123: {fieldIndex: 123, fieldName: {my_field_name: 0}, ctor: proto.example.MyMessage} }
 *
 * fieldName contains the JsCompiler renamed field name property so that it
 * works in OPTIMIZED mode.
 *
 * @type {!Object<number, jspb.ExtensionFieldInfo>}
 */
TestExtensionsMessage.extensions = {};


/**
 * The extensions registered with this message class. This is a map of
 * extension field number to fieldInfo object.
 *
 * For example:
 *     { 123: {fieldIndex: 123, fieldName: {my_field_name: 0}, ctor: proto.example.MyMessage} }
 *
 * fieldName contains the JsCompiler renamed field name property so that it
 * works in OPTIMIZED mode.
 *
 * @type {!Object<number, jspb.ExtensionFieldBinaryInfo>}
 */
TestExtensionsMessage.extensionsBinary = {};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
TestExtensionsMessage.prototype.toObject = function(opt_includeInstance) {
  return TestExtensionsMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!TestExtensionsMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
TestExtensionsMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
intfield: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f
  };

  jspb.Message.toObjectExtension(/** @type {!jspb.Message} */ (msg), obj,
      TestExtensionsMessage.extensions, TestExtensionsMessage.prototype.getExtension,
      includeInstance);
  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


export class ExtensionMessage extends jspb.Message {
  /**
   * Generated by JsPbCodeGenerator.
   * @param {Array=} opt_data Optional initial data array, typically from a
   * server response, or constructed directly in Javascript. The array is used
   * in place and becomes part of the constructed object. It is not cloned.
   * If no data is provided, the constructed object will be empty, but still
   * valid.
   * @extends {jspb.Message}
   * @constructor
   */
  constructor(opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
  };
  /**
   * optional string ext1 = 1;
   * @return {string}
   */
  getExt1() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
  };


  /**
   * @param {string} value
   * @return {!ExtensionMessage} returns this
   */
  setExt1(value) {
    return jspb.Message.setField(this, 1, value);
  };


  /**
   * Clears the field making it undefined.
   * @return {!ExtensionMessage} returns this
   */
  clearExt1() {
    return jspb.Message.setField(this, 1, undefined);
  };


  /**
   * Returns whether this field is set.
   * @return {boolean}
   */
  hasExt1() {
    return jspb.Message.getField(this, 1) != null;
  };


  /**
   * Deserializes binary data (in protobuf wire format).
   * @param {jspb.ByteSource} bytes The bytes to deserialize.
   * @return {!ExtensionMessage}
   */
  static deserializeBinary(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new ExtensionMessage;
    return ExtensionMessage.deserializeBinaryFromReader(msg, reader);
  };


  /**
   * Deserializes binary data (in protobuf wire format) from the
   * given reader into the given message object.
   * @param {!ExtensionMessage} msg The message object to deserialize into.
   * @param {!jspb.BinaryReader} reader The BinaryReader to use.
   * @return {!ExtensionMessage}
   */
  static deserializeBinaryFromReader(msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      var field = reader.getFieldNumber();
      switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.setExt1(value);
        break;
      default:
        reader.skipField();
        break;
      }
    }
    return msg;
  };


  /**
   * Serializes the message to binary data (in protobuf wire format).
   * @return {!Uint8Array}
   */
  serializeBinary() {
    var writer = new jspb.BinaryWriter();
    ExtensionMessage.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
  };


  /**
   * Serializes the given message to binary data (in protobuf wire
   * format), writing to the given BinaryWriter.
   * @param {!ExtensionMessage} message
   * @param {!jspb.BinaryWriter} writer
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  static serializeBinaryToWriter(message, writer) {
    var f = undefined;
    f = /** @type {string} */ (jspb.Message.getField(message, 1));
    if (f != null) {
      writer.writeString(
        1,
        f
      );
    }
  };


}

if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  ExtensionMessage.displayName = 'proto.jspb.test.ExtensionMessage';
}

/**
 * A tuple of {field number, class constructor} for the extension
 * field named `extField`.
 * @type {!jspb.ExtensionFieldInfo<!ExtensionMessage>}
 */
ExtensionMessage.extField = new jspb.ExtensionFieldInfo(
    100,
    {extField: 0},
    ExtensionMessage,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         ExtensionMessage.toObject),
    0);


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
ExtensionMessage.prototype.toObject = function(opt_includeInstance) {
  return ExtensionMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!ExtensionMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
ExtensionMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
ext1: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}



TestExtensionsMessage.extensionsBinary[100] = new jspb.ExtensionFieldBinaryInfo(
    ExtensionMessage.extField,
    jspb.BinaryReader.prototype.readMessage,
    jspb.BinaryWriter.prototype.writeMessage,
    ExtensionMessage.serializeBinaryToWriter,
    ExtensionMessage.deserializeBinaryFromReader,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
TestExtensionsMessage.extensions[100] = ExtensionMessage.extField;

export class ForeignNestedFieldMessage extends jspb.Message {
  /**
   * Generated by JsPbCodeGenerator.
   * @param {Array=} opt_data Optional initial data array, typically from a
   * server response, or constructed directly in Javascript. The array is used
   * in place and becomes part of the constructed object. It is not cloned.
   * If no data is provided, the constructed object will be empty, but still
   * valid.
   * @extends {jspb.Message}
   * @constructor
   */
  constructor(opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
  };
  /**
   * optional Deeply.Nested.Message deeply_nested_message = 1;
   * @return {?protos_test_pb.Deeply.Nested.Message}
   */
  getDeeplyNestedMessage() {
    return /** @type{?protos_test_pb.Deeply.Nested.Message} */ (
      jspb.Message.getWrapperField(this, protos_test_pb.Deeply.Nested.Message, 1));
  };


  /**
   * @param {?protos_test_pb.Deeply.Nested.Message|undefined} value
   * @return {!ForeignNestedFieldMessage} returns this
  */
  setDeeplyNestedMessage(value) {
    return jspb.Message.setWrapperField(this, 1, value);
  };


  /**
   * Clears the message field making it undefined.
   * @return {!ForeignNestedFieldMessage} returns this
   */
  clearDeeplyNestedMessage() {
    return this.setDeeplyNestedMessage(undefined);
  };


  /**
   * Returns whether this field is set.
   * @return {boolean}
   */
  hasDeeplyNestedMessage() {
    return jspb.Message.getField(this, 1) != null;
  };


  /**
   * Deserializes binary data (in protobuf wire format).
   * @param {jspb.ByteSource} bytes The bytes to deserialize.
   * @return {!ForeignNestedFieldMessage}
   */
  static deserializeBinary(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new ForeignNestedFieldMessage;
    return ForeignNestedFieldMessage.deserializeBinaryFromReader(msg, reader);
  };


  /**
   * Deserializes binary data (in protobuf wire format) from the
   * given reader into the given message object.
   * @param {!ForeignNestedFieldMessage} msg The message object to deserialize into.
   * @param {!jspb.BinaryReader} reader The BinaryReader to use.
   * @return {!ForeignNestedFieldMessage}
   */
  static deserializeBinaryFromReader(msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      var field = reader.getFieldNumber();
      switch (field) {
      case 1:
        var value = new protos_test_pb.Deeply.Nested.Message;
        reader.readMessage(value,protos_test_pb.Deeply.Nested.Message.deserializeBinaryFromReader);
        msg.setDeeplyNestedMessage(value);
        break;
      default:
        reader.skipField();
        break;
      }
    }
    return msg;
  };


  /**
   * Serializes the message to binary data (in protobuf wire format).
   * @return {!Uint8Array}
   */
  serializeBinary() {
    var writer = new jspb.BinaryWriter();
    ForeignNestedFieldMessage.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
  };


  /**
   * Serializes the given message to binary data (in protobuf wire
   * format), writing to the given BinaryWriter.
   * @param {!ForeignNestedFieldMessage} message
   * @param {!jspb.BinaryWriter} writer
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  static serializeBinaryToWriter(message, writer) {
    var f = undefined;
    f = message.getDeeplyNestedMessage();
    if (f != null) {
      writer.writeMessage(
        1,
        f,
        protos_test_pb.Deeply.Nested.Message.serializeBinaryToWriter
      );
    }
  };


}

if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  ForeignNestedFieldMessage.displayName = 'proto.jspb.test.ForeignNestedFieldMessage';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
ForeignNestedFieldMessage.prototype.toObject = function(opt_includeInstance) {
  return ForeignNestedFieldMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!ForeignNestedFieldMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
ForeignNestedFieldMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
deeplyNestedMessage: (f = msg.getDeeplyNestedMessage()) && protos_test_pb.Deeply.Nested.Message.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}



/**
 * A tuple of {field number, class constructor} for the extension
 * field named `floatingMsgField`.
 * @type {!jspb.ExtensionFieldInfo<!ExtensionMessage>}
 */
export const floatingMsgField = new jspb.ExtensionFieldInfo(
    101,
    {floatingMsgField: 0},
    ExtensionMessage,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         ExtensionMessage.toObject),
    0);

TestExtensionsMessage.extensionsBinary[101] = new jspb.ExtensionFieldBinaryInfo(
    floatingMsgField,
    jspb.BinaryReader.prototype.readMessage,
    jspb.BinaryWriter.prototype.writeMessage,
    ExtensionMessage.serializeBinaryToWriter,
    ExtensionMessage.deserializeBinaryFromReader,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
TestExtensionsMessage.extensions[101] = floatingMsgField;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `floatingStrField`.
 * @type {!jspb.ExtensionFieldInfo<string>}
 */
export const floatingStrField = new jspb.ExtensionFieldInfo(
    102,
    {floatingStrField: 0},
    null,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         null),
    0);

TestExtensionsMessage.extensionsBinary[102] = new jspb.ExtensionFieldBinaryInfo(
    floatingStrField,
    jspb.BinaryReader.prototype.readString,
    jspb.BinaryWriter.prototype.writeString,
    undefined,
    undefined,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
TestExtensionsMessage.extensions[102] = floatingStrField;

